name = "24K POS Barcode Scanner"
client_id = ""
application_url = "https://example.com"
embedded = false
handle = "24k-pos-barcode-scanner"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]
